name: Cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Component Test
        uses: cypress-io/github-action@v4
        with:
          component: true

      - name: e2e Test
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: npm start
          wait-on: 'http://localhost:4000'
